# build stage
FROM maven:3.9-amazoncorretto-17 AS build
WORKDIR /app

COPY . .

RUN mvn clean package

# run stage
FROM tomcat:10.0.27-jre17

COPY --from=build /app/target/tv_addicts_system.war $CATALINA_HOME/webapps/